on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - run: |
            ./mvnw spring-boot:build-image
            docker tag spring-petclinic:3.1.0 ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring-petclinic:3.1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring-petclinic:3.1.0

        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Run Azure webapp deploy action using publish profile credentials'
          uses: azure/webapps-deploy@v3
          with: 
            app-name: spring-petclinic-1753128135832
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/spring-petclinic:3.1.0'